---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleeet-control
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./module/config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: fleeet-config
  patches:
    - patch: |-
        - op: replace
          path: /spec/template/spec/containers/0/imagePullPolicy
          value: Always
      target:
        group: apps
        version: v1
        kind: Deployment
        name: controller-manager
